# Generated by Django 5.2.4 on 2025-07-13 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Saying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('translation', models.TextField()),
                ('explanation', models.TextField()),
                ('culture', models.CharField(choices=[('Greek', 'Ancient Greek'), ('Hebrew', 'Hebrew')], max_length=30)),
                ('tone', models.CharField(choices=[('joyful', 'Joyful'), ('cautionary', 'Cautionary'), ('solemn', 'Solemn'), ('reflective', 'Reflective'), ('humorous', 'Humorous')], max_length=30)),
                ('source', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SavedSayings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Saved_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('saying', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_app.saying')),
            ],
        ),
        migrations.CreateModel(
            name='Reflections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('saying', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_app.saying')),
            ],
        ),
    ]
